version: "3.2"
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "numsey#2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
        - rabbitmq_netcore
  web:
    build:
      context: .
      dockerfile: ./src/web/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql-server;Database=auth;User Id=sa;Password=numsey#2021;
      - ConnectionStrings__ChatConnection=Server=mssql-server;Database=chat;User Id=sa;Password=numsey#2021;
    ports: 
      - "8563:80"
    networks:
        - rabbitmq_netcore
    depends_on:
      - rabbitmq
      - mssql-server
  api:
    build:
      context: .
      dockerfile: ./src/api/Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql-server;Database=auth;User Id=sa;Password=numsey#2021;
      - ConnectionStrings__ChatConnection=Server=mssql-server;Database=chat;User Id=sa;Password=numsey#2021;
    ports: 
      - "8564:80"
    networks:
        - rabbitmq_netcore
    depends_on:
      - rabbitmq
      - mssql-server
  bot:
    build:
      context: .
      dockerfile: ./src/bot/Bot/Dockerfile
    networks:
        - rabbitmq_netcore         
    depends_on:
      - rabbitmq
      - mssql-server
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_netcore

networks:
  rabbitmq_netcore:
    driver: bridge